### ISSUE TITLE
如何解决按下Ctrl就直接打开浏览器的问题？

### ISSUE THREAD

**Issue by xluos** [thx/vscode-magix#4]
我这边儿实现时发现跳转浏览器时找不到合适的Location对象来返回，如果在provideDefinition方法中直接打开浏览器的话，provideDefinition是在按下Ctrl时就会触发，而不是点击鼠标时触发。

问一下你这边儿是怎么解决这个问题的？看了你的代码没有看到在哪里处理这个问题

**Comment by wudi3** [comment]
我也没有很好的解决按下Ctrl就多次触发打开浏览器的问题。不过做了一些优化，在class 里面定义一个时间变量lastTriggerTime，每次调用对比当前时间和lastTriggerTime，当两者时间差大于一个阈值就触发打开浏览器操作。能多少避免多次打开浏览器的问题。
![image](https://user-images.githubusercontent.com/6203854/83251339-124af200-a1dc-11ea-803f-9f8b54818b0e.png)
